# Generated by Django 3.2.15 on 2023-01-04 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 11, 3, 8, 90583)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 11, 3, 8, 91581)),
        ),
    ]
