# Generated by Django 3.2.15 on 2023-01-04 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_auto_20230104_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 11, 4, 59, 515243)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 11, 4, 59, 516238)),
        ),
    ]
