# Generated by Django 3.2.15 on 2023-01-05 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_auto_20230104_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 18, 52, 18, 520614)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 18, 52, 18, 521613)),
        ),
    ]
