# Generated by Django 3.2.15 on 2023-01-05 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_auto_20230104_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='b2b.customers'),
        ),
        migrations.AlterField(
            model_name='item',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 19, 0, 30, 338021)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 19, 0, 30, 338021)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='b2b.customers'),
        ),
    ]
